spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring?useTimezone=true&serverTimeZone=UTC
    username: root
    password: 12345
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    #properties:
     # hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true